### ISSUE TITLE
Hash Map

### ISSUE THREAD

**Issue by hcps-larkinch** [Voter-Data-Project/PurpleAmerica#22]
I'm confused on how the code for the hash map works. I don't get how the map is adding color and drawing. It is making it confusing to add code myself.

**Comment by hcps-larkinch** [comment]
Also what does getAbsoluteFile() doing? How is it different from just putting in the file paths?

**Comment by SeanofLaRochelle** [comment]
So Hash Maps are confusing because they violate rules we know. Hash Maps are like arrays except the indexes are not numbered, but named. A better explanation would be a real life example. A Hash Map is a bank, and the name/key is like a pin number. To access a person's account, the pin number is needed. In a Hash Map, an object is placed in a Hash Map, just like a person's money, but instead of a pin number we use a String to access the object. Color is the object and the state name is the key. The program determines the state's color and then adds the color to the Hash Map with the state's name as the key. When the program goes through and draws the states, it will read the state's name a use it to find the Color in the Hash Map. Color needs to casted as a Color object because the program only knows it is an object when it is pulled out of the Hash Map. 

`HashMap colorMap = new HashMap(); //HashMap that holds colors for each state
                                                  //or county
                HashMap colorHolder = new HashMap(); //HashMap that holds the color for each
                                                    //county in the United States`
This is the initialization of the Hash Maps. In our project

This section of code adds Color objects to the Hash Map and assigns the state name as the key.
`for(int i = 0; i < u; i++){
                                            electionData = scan2.nextLine(); //Grabs the entire line of input
                                            dataLine = electionData.split(","); //Splits it at every comma
                                            subSection = dataLine[0]; //Takes the county name
                                            int[] voterData = new int[3]; //Creates an array to hold the vote numbers
                                            voterData[0] = Integer.parseInt(dataLine[1]);
                                            voterData[1] = Integer.parseInt(dataLine[2]);
                                            voterData[2] = Integer.parseInt(dataLine[3]);
                                            stateColor = (phil.colorStates(voterData)); //Creates the custom color
                                            colorHolder.put(subSection.toLowerCase(), stateColor); //Adds it to the HashMap`

This is where we retrieve the color in the code.
`map.setPenColor((Color)colorHolder.get(subName.toLowerCase())); //Sets the pen color
                                                                                                  //to the corresponding color
                                                                                                  //of the county`

In order to make a Hash Map, just do what you do with every object. Initialize a new instance of it.
`HashMap nameOfHashMap = new HashMap()`

To add an object to the Hash Map, you must use the put() method. This will place the object into the Hash Map with an assigned key. The arguments for a Hash Map are the String that will be used as a key and the object. For more detail go to the Java Api and look up Hash Maps
`nameOfHashMap.put("Key", Object);`

To get an element from a Hash Map, you must use the get() method. The only argument for the get() method is the String that is the key. For more detail go to the Java Api.
`nameOfHashMap.get("Key");`
This will return an object, but not a type of object. You will need to use `(Color)` or `(java.awt.Color)` to cast the object as a custom color.

**Comment by SeanofLaRochelle** [comment]
Sorry the code looks a bit jumbled, I don't really understand how gitHub formats code.

**Comment by SeanofLaRochelle** [comment]
So, the .getAbsoluteFile() is a function in the File class necessary for creating a relative path.

**Comment by SeanofLaRochelle** [comment]
Basically, how it works it the String you see ("src/data/" + state + ".txt") is used to create a new File, but that path points to absolutely nothing. But it is a piece of an actual path.

**Comment by SeanofLaRochelle** [comment]
Unfortunately, the absolute file path for each of us is very different due to how we set up the project.

**Comment by SeanofLaRochelle** [comment]
This part of the path is the only part of the path we have in common. Once the File is created using this path it is placed in a Scanner. However, the Scanner needs the absolute path. In order to get the absolute path, we use the .getAbsoluteFile() method. What this does is it scans the entire computer for a path with that exact section of the path. Once it finds it (since only one path can have the section),  it will return that absolute file path. Those giving the Scanner the absolute file path that it needs.

**Comment by hcps-larkinch** [comment]
So is there a part of the code that makes the file path skip over the Alaska.txt and Hawaii.txt files?

**Comment by SeanofLaRochelle** [comment]
No, AK.txt and HI.txt are never read.When the user selects a state, the variable state holds that value. So when the relative file path is created, it uses that value. For example "src/data/" + state +".txt" is the relative file path. If the user selects Virginia, the file path becomes "src/data/VA.txt"
