### ISSUE TITLE
Alaska/Hawaii

### ISSUE THREAD

**Issue by hcps-larkinch** [Voter-Data-Project/PurpleAmerica#23]
I need to set a new scale in order to draw Alaska and Hawaii, but I can't figure out where to add it. Should I make another method to set the new scale or should is there a place in the drawing method I can add to?

**Comment by SeanofLaRochelle** [comment]
You could make a different method, but I suggest making playing around with the points until you get close to where you want it. I suggest copying a playing around with the section of code
`xVal[] = scan.nextDouble();`
`yVal[] = scan.nextDouble();`

You will need to copy or remake the arrays in order to do this.

**Comment by SeanofLaRochelle** [comment]
I hope this helps

**Comment by hcps-larkinch** [comment]
Ok thank you! And also, I remember you mentioning something about how the program doesn't deal the AK files and HI files right now, but is there somewhere that you prevented the files from being looked over?

**Comment by SeanofLaRochelle** [comment]
Yes, if you want to handle the files separately from the other files. I suggest using scan.hasNextInt() to detect the "name" of the Hawaiian counties. After getting the number that represents the name, skip the next line since it is just the abbreviation for the state, and use the third number to set up the for loop of the arrays I showed you in the earlier comment. I suggest seeing what each section draws before coloring, the issue is that county names on the drawing file do not correspond with the voting file so you will have to look up the area names. For Alaska, just use scan.nextLine() to get the entire name of the county, then skip the next line and then get the number and use that for the for loop.
